cornell-zhang/heterocl

hlib/python/setup.py
python/heterocl/compute_api.py
python/setup.py
tests/test_compute_basic.py

Originally we do not support return statements inside compute APIs with multiple dimensions. The reason is that the indices of the tensors will be cast automatically, which results in incorrect behaviors in LLVM/CPU execution. Now the indices are unchanged. Following is a runnable example.
```python
A = hcl.placeholder(10, 10, 10)
def compute(val):
with hcl.if_(val > 0):
hcl.return_(val)
with hcl.else_():
hcl.return_(0)
B = hcl.compute(A.shape, lambda *args: compute(A[args]))
```
This is also added as a test case.

[API] Fix hcl.return_ within compute APIs

---

tests/test_codegen_soda.py
tvm/src/codegen/codegen_soda.cc
tvm/src/codegen/codegen_soda.h

Since the ternary operator is not supported in SODA, HeteroCL need to generate `select(condition, true_value, false_value)` instead of `condition ? true_value : false_value`.

[Backend][SODA]: Generate valid SODA code

---

python/heterocl/tvm/intrin.py
tests/test_compute_intrinsic.py
tests/test_compute_reduce.py
tvm/src/codegen/llvm/codegen_llvm.cc

In this PR, we also move some of the typecasting to LLVM level. This allows other backends to decide what to do when having intrinsic calls with different types.

[API][Backend] Enable using constants in intrinsic calls

---

docs/source/heterocl.compute_api.rst
python/heterocl/compute_api.py
samples/black_scholes/black_scholes.py
samples/digitrec/digitrec_main.py
samples/fft/fft.py
samples/kmeans/kmeans_main.py
samples/sgd/sgd.py
samples/smith_waterman/smith_waterman_main.py
samples/unsharp/unsharp.py
tests/test_c.py
tests/test_dsl_basic.py
tests/test_dsl_def.py
tutorials/tutorial_02_imperative.py

The old API name may be confusing. That's why we should use `hcl.scalar` instead. Also, some examples are updated with the usage of `x.v` instead of `x[0]`.

[API] Rename hcl.local to hcl.scalar

---

python/heterocl/api.py
python/heterocl/tvm/build_module.py
tests/test_api.py

With this PR, now the users can directly build a HeteroCL function with manually built IR. An example is shown in the [tests](https://github.com/cornell-zhang/heterocl/blob/master/tests/test_api.py).
@Blaok, let me know if you need more functionality.

[API] Enable building a function directly from IR

---

python/heterocl/api.py

A quick fix to #134. Now the "select" API should have the same behavior as TVM's "select" API. The following examples should be working.
```python
select(2 > 1, x, y)
select(0, True, False)
select(True, 50, 60)
```

[API] Enable select API to accept Python expressions

---

python/heterocl/mutator.py

Originally, in CastRemover, we removed all the casted data types, this creates problems when we want to access the data type of the variables.

[API] Fixed incorrect casting for select in CastRemover

---

.circleci/config.yml

Starting from 2020, Python 2 is no longer supported by the community. Thus, we also remove the tests for Python 2 for HeteroCL.

[API] Remove support for Python 2

---

tests/test_compute_intrinsic.py
tvm/src/codegen/llvm/codegen_llvm.cc

The original codegen was incorrect because it assumes the inputs are all floating points.

[Backend] Fix LLVM CodeGen for intrinsics

---

python/heterocl/compute_api.py
python/heterocl/schedule.py
tests/test_compute_basic.py

With this PR, now users can create a HeteroCL tensor from a Python list or a Numpy array by using the existing ``hcl.copy`` API. An example is shown below.
```python
arr = [[1, 2, 3], [4, 5, 6]]
A = hcl.copy(arr, "A", hcl.Int())
s = hcl.create_schedule([A])
```
The ``arr`` in the above example can also be a Numpy array. More examples can be seen under the tests folder.

[API][v0.3] Add Support for Copying From a Python List or Numpy Array

---

tests/test_schedule_memory.py
tvm/src/pass/generate_reuse_buffer.cc

This solves part of the problem in #155. Several tests are added to check the correctness under arbitrary shapes.
The issue comes from the wrong index flattening given a tuple of indices and the shape. It turns out to be just a single line fix.

[API] Fix Wrong Index Calculation in API reuse_at

---

hlib/python/hlib/op/nn.py
python/heterocl/api.py
python/heterocl/compute_api.py
python/heterocl/dsl.py
python/heterocl/nparray.py
python/heterocl/schedule.py
python/heterocl/tensor.py
python/heterocl/types.py
python/heterocl/util.py
tests/test_dtype.py
tvm/HalideIR/src/ir/IR.cpp
tvm/HalideIR/src/ir/IR.h
tvm/src/codegen/codegen_c.cc
tvm/src/codegen/hlsc/codegen_vhls.cc
tvm/src/codegen/llvm/codegen_llvm.cc

In this PR, we introduce the C-like struct to HeteroCL. 
Users can define a HeteroCL type by using ``hcl.struct`` with a Python dictionary. The following shows an example.
```python
ts = hcl.Struct({"fa": hcl.Int(8), "fb": hcl.Fixed(8, 2), "fc": hcl.Float()})
``` 
Note that currently, we only support single-level structs. Namely, we cannot have a struct inside another struct. Since HeteroCL does not support pointers intrinsically, we will not have pointer members or self-referential structs.
Users can print the struct simply using Python ``print`` function. The following are some examples of getting information of a struct.
```python
print(ts)
print(ts.fa)
print(ts["fa"])
```
With the support of a struct, we can create tensors having struct type. For example,
```python
A = …
```

[API][v0.3] Introduce Struct Data Type to HeteroCL

---

tests/test_schedule_memory.py
tvm/src/pass/generate_reuse_buffer.cc
tvm/src/schedule/schedule_dataflow_rewrite.cc

In this PR, we will implement the following features.
With the existing ``reuse_at`` primitive, we assume that there is no user-specified padding. However, padding is everywhere. Thus, we need to be able to correctly infer the bound where the data will be stored in the reuse buffers. Following we show two examples that should work correctly after this PR.
```python
A = hcl.placeholder((10,))
r = hcl.reduce_axis(0, 3)
B = hcl.compute((8, ), lambda x: hcl.sum(A[x+r], axis=r))
s = hcl.create_schedule([A, B])
s.reuse_at(A, s[B], B.axis[0])
A = hcl.placeholder((10,))
r = hcl.reduce_axis(0, 3)
B = hcl.compute(
(10, ), 
lambda x: hcl.select(x == 0, A[x] + A[x+1],
hcl.select(x == 9, A[x-1] + A[x], hcl.sum(A[x-1+r], axis=r))))
```
The users can definitely create another stage for padding tensor …

[WIP][API] Enhance the Current Support for Reuse Buffers

---

python/heterocl/dsl.py
python/heterocl/tvm/build_module.py
tests/test_dsl_def.py
tvm/HalideIR/src/ir/IR.cpp
tvm/HalideIR/src/ir/IR.h
tvm/HalideIR/src/ir/IRMutator.cpp
tvm/HalideIR/src/ir/IRPrinter.cpp
tvm/HalideIR/src/ir/IRVisitor.cpp
tvm/src/api/api_ir.cc
tvm/src/codegen/codegen_c.cc
tvm/src/codegen/hlsc/codegen_vhls.cc
tvm/src/codegen/opencl/codegen_aocl.cc
tvm/src/pass/ir_mutator.cc
tvm/src/pass/storage_flatten.cc
tvm/src/schedule/schedule_dataflow_rewrite.cc

In this PR, we enable using declarative code along with hcl.def. Following is an example.
```python                                                                                                                                                                                               
@hcl.def_([a.shape, b.shape, c.shape])                                                                                                                                                           
def add(a, b, c):                                                                                                                                                                                
d = hcl.compute(a.shape, lambda *x: a[x] + b[x], "d") …
```

[API] Enable declarative code with hcl.def

---

hlib/python/hlib/frontend/relay_parser.py

Modify the import path according to this [TVM PR](https://github.com/apache/incubator-tvm/pull/5087).

[API] Change import tvm.relay.expr.Function to tvm.relay.function.Function

---

python/heterocl/api.py
python/heterocl/compute_api.py
python/heterocl/dsl.py
python/heterocl/schedule.py
python/heterocl/tvm/stmt.py
tests/test_api_print.py
tests/test_api_print_cases/print_expr.py
tests/test_api_print_cases/print_number.py
tests/test_api_print_cases/print_tensor_1D.py
tests/test_api_print_cases/print_tensor_2D.py
tests/test_dsl_basic.py
tvm/HalideIR/src/ir/Expr.h
tvm/HalideIR/src/ir/IR.cpp
tvm/HalideIR/src/ir/IR.h
tvm/HalideIR/src/ir/IRMutator.cpp
tvm/HalideIR/src/ir/IRMutator.h
tvm/HalideIR/src/ir/IRPrinter.cpp
tvm/HalideIR/src/ir/IRVisitor.cpp
tvm/HalideIR/src/ir/IRVisitor.h
tvm/include/tvm/ir.h
tvm/include/tvm/ir_functor_ext.h
tvm/include/tvm/ir_mutator.h
tvm/include/tvm/ir_visitor.h
tvm/src/api/api_ir.cc
tvm/src/codegen/llvm/codegen_llvm.cc
tvm/src/codegen/llvm/codegen_llvm.h
tvm/src/codegen/llvm/llvm_module.cc
tvm/src/lang/ir.cc
tvm/src/pass/ir_mutator.cc
tvm/src/pass/ir_visitor.cc

1. In this PR, we introduce a new API ``hcl.print``, which can print HeteroCL objects. Currently, the functionality is still very basic. In other words, we cannot generate pretty print like NumPy.
2. I also removed the need for using ``hcl.Stage`` at the top-level. A default top-level Stage will be generated automatically. Please refer to ``test_dsl_basic.py`` for more examples.
1. Print an expression
```python
A = hcl.compute((10,), lambda x: x)
hcl.print(A[0])
hcl.print(A[0], "A[0]: %d\n")
hcl.print([A[0], A[1]])
hcl.print([A[0], A[1]], "0: %d, 1: %d\n")
hcl.print(5)
```
More details: for integers, by default we use "%d". For all other data types including floating points and fixed points, we use "%f".
2. Print a Tensor or a slice of Tensor
```python
A = hcl.compute((3, 3), lambda x, y: …
```

[API] Adding printing function to HeteroCL

---

tests/test_dtype.py
tvm/HalideIR/src/ir/IR.cpp

The default Halide behavior for handling constant int is incorrect when handling bitwidth greater than 64. This PR fixed this problem by commenting out the behaviors that normalize the values in ``IR.cpp``.

[Backend] Fixed Incorrect Behavior When Casting Constants to Very Long Int

---

python/heterocl/api.py
tests/test_api_print.py
tests/test_api_print_cases/print_expr.py
tvm/src/codegen/llvm/codegen_llvm.cc

In this PR, we fix the issue in #183. Now we can print up to 64-bit integers and double-precision floating points.

[API][Backend] Fix hcl.print with UInt supported

---

tests/test_codegen_vhls.py
tvm/src/codegen/codegen_c.cc
tvm/src/codegen/hlsc/codegen_vhls.cc

1. Fixed the ternary ops generation logic in Vivado HLS CodeGen. 
2. Fixed the function signature for legacy Vivado HLS CodeGen.
3. New test cases in vhls code generator testing.
Should fix #198 and #193. When generating the ternary ops in VHLS, HeteroCL will check the data type for each expressions. The checking logic will avoid duplicate dtype casting.

[Backend] Fix Vivado HLS CodeGen for data type casting 

---

tests/test_codegen_soda.py
tests/test_codegen_vhls.py
tvm/HalideIR/src/ir/IROperator.cpp
tvm/src/codegen/codegen_c.cc
tvm/src/codegen/hlsc/codegen_vhls.cc

This PR solves the data type casting error in VHLS code generator, which should address the following two problems:
1. Casting fixed-point value to integer (causing precision problem). Brief example showing the minimal test case and which function caused the error. 
```python
A = hcl.placeholder((8, 8), "A", dtype=hcl.Int(20))
B = hcl.placeholder((8, 8), "B", dtype=hcl.Fixed(16,12))
def kernel(A, B):
return hcl.compute((8, 8), lambda y, x:
hcl.select(x < 4, A[y][x], B[y][x]), "C", dtype=hcl.Int(8))
```
With the example above, HeteroCL casts fixed point value B[y, x] into ap_int<20>, which makes B[y, x] lose all the fractional bits. The issue happens when ternary operation is generated with implicit data type casting. i.e., the two branches in select expression are compared, then HeteroCL …

[Backend] Fix Vivado HLS CodeGen for Data Type Casting

---

tests/test_dtype.py
tvm/include/tvm/expr.h
tvm/src/runtime/c_runtime_api.cc

For CPU memory allocation, it actually calls the TVM builtin function instead of using LLVM's alloc command. Previously, we only tested on small input arrays, which are automatically unrolled by LLVM. That's why the bug was not caught. In this PR, we fixed the memory allocation with the correct allocation size in terms of the number of bytes.
The place where TVM replace the allocation node with its builtin function is in `pass/lower_tvm_builtin.cc`. And the place where the allocation size is calculated is in `include/tvm/expr.h`.
Tests will be added later.

[Backend] Fixed incorrect memory allocation for fixed points on CPU

---

samples/sobel/sobel_sdsoc.py
tests/test_runtime_build.py
tvm/src/codegen/build_common.cc
tvm/src/codegen/build_util.cc
tvm/src/codegen/build_util.h
tvm/src/codegen/hlsc/codegen_vhls.cc
tvm/src/codegen/hlsc/codegen_vhls.h
tvm/src/codegen/opencl/codegen_aocl.cc
tvm/src/codegen/opencl/codegen_xocl_host.cc

The main difference between SDSoC VHLS code and Vitis/SDAccel is the system memory allocation APIs (SDSoC uses `sds_alloc` and `sds_free`) and kernel function header pragmas. 
1. Use `sds_alloc` for memory allocation on host program 
2. Modified `StreamExpr` to contain index information (this can be also useful for the access pattern analysis in the next streaming enhancement PR)
Example of compiling with SDSoC in python
```python
target = hcl.platform.zc706
s = hcl.create_schedule([A], kernel)
s.to(kernel.B, target.xcel)
s.to(kernel.C, target.host)
target.config(compile="sdsoc", mode="sw_sim")
f = hcl.build(s, target)
```
Example of generated host code:
```c++
ap_int<32>* B_channel = sds_alloc(sizeof(ap_int<32>)*10*32);
for (ap_int<32> B0 = 0; B0 < 10; ++B0) {
for (ap_int<32> B1 = 0; B1 …
```

[Backend] VHLS CodeGen SDSoC mode (legacy support)

---

tests/test_codegen_vhls.py
tvm/src/codegen/codegen_c.cc

Issue: the immediate const number is not cast by the code generator when it has bitwidth of 32-bits. And we can fix it by enforcing the type casting regardless of the bitwidth.

[Backend] Fix VHLS CodeGen immediate data type casting

---

tvm/src/schedule/schedule_dataflow_rewrite.cc

According to the C++ document, it is ill-formed to bind a temporary (an unnamed variable) to a reference member in a constructor initializer list. [[link1](https://en.cppreference.com/w/cpp/language/lifetime)] [[link2](https://en.cppreference.com/w/cpp/language/lifetime)]
Following is an example provided by the document.
```c++
struct A {
A() : v(42) { }   // error
const int& v;
};
```

[Pass] Fix Ill-Formed C++ Code in reuse_at

---

docker/Dockerfile

The users can pull and run the docker image with the following commands: 
```shell
docker pull hecmay/heterocl:0.3
docker run -it hecmay/heterocl:0.3 bash
source /opt/conda/etc/profile.d/conda.sh
conda activate py36
```

[Testing][Utils] Docker Image for HeteroCL

---

python/heterocl/tvm/expr.py
tests/test_dsl_basic.py

In this PR, we enable getting bit/slice from expressions.
```python
A = hcl.placeholder((10,))
B = hcl.compute(A.shape, lambda x: (A[x]+1)[5])
```
For more examples, please refer to `tests/test_dsl_basic.py`.

[API] Add support for getting bit/slice from expressions

---

python/heterocl/tvm/build_module.py
tests/test_codegen_vhls.py

This pass is inherited from TVM. It will rewrite any `select` expression with `Load` into a TVM intrinsic `tvm_if_then_else`. This pass is not really useful to us so we can safely remove it. This will also solve #232.

[Pass] Remove pass: rewrite_unsafe_select

---

tests/test_codegen_vhls.py
tvm/src/codegen/codegen_c.cc

In this PR, the VHLS code generation for `Select` is fixed. Moreover, I bring back the original tests before removing `rewrtie_unsafe_select` (#237) to make sure we indeed generate the correct code.

[Backend][Testing] Fix VHLS codegen for Select; Recover original tests

---

hlib/python/setup.py
hlib/tests/test_extern_ip.py
python/heterocl/report.py
python/heterocl/tvm/build_module.py
python/heterocl/tvm/module.py
tests/test_runtime_build.py
tvm/src/template/vivado/Makefile

This PR fixes #246 that HeteroCL outputs out-of-date HLS reports when the program is synthesized several times. By enforcing HeteroCL to regenerate json output, the retrieved HLS report will be up-to-date.

[API] Fix out-of-date HLS reports

---

python/heterocl/api.py
python/heterocl/devices.py
python/heterocl/report.py
python/heterocl/schedule.py
python/heterocl/tvm/build_module.py
python/heterocl/tvm/module.py
python/heterocl/tvm/runtime.py
tests/test_runtime_build.py
tvm/src/codegen/build_common.cc
tvm/src/codegen/build_util.cc
tvm/src/codegen/build_util.h
tvm/src/codegen/opencl/codegen_xocl_host.cc
tvm/src/template/vivado/Makefile

This PR will fix #252 . Users can specify where they want to store and execute their projects by `target.config(project="path/to/project")`.
Following is a full example generating two programs of different schedules and also retaining their results in different folders.
```python
def gemm():
dtype = hcl.Float()
M = 64
K = 64
N = 64
A = hcl.placeholder((M, K), "A", dtype=dtype)
B = hcl.placeholder((K, N), "B", dtype=dtype)
k = hcl.reduce_axis(0, K)
def kernel(A, B):
C = hcl.compute((M, N), lambda x, y: hcl.sum(A[x, k] * B[k, y], axis=k, dtype=dtype), "C", dtype=dtype)
return C
def make_schedule(opt=False,project="gemm"):
s = hcl.create_schedule([A, B], kernel)
target = hcl.platform.zc706
target.config(compile="vivado_hls", mode="csyn", project=project) # note this line
s.to([A, …
```

[API] Add user-defined project folder support

---

python/heterocl/tensor.py
tests/test_dtype.py

In this PR, we fix the data types for the following cases.
```python
stype = hcl.Struct({"fa": hcl.Int(8), "fb": hcl.Fixed(13, 11), "fc": hcl.Float()})
D = hcl.compute(A.shape, lambda x: (x, x, x), dtype=stype)
print(D[0].fa.dtype) # => should be "int8"
A = hcl.compute(..., dtype=hcl.Int(32))
print(A[0][0:2].dtype) # => should be "int2"
print(A[0][A[0]: A[0]+1].dtype) # => should be "int1"
print(A[0][A[0] : A[3]].dtype) # => should be "int32"
```

[API] Fix showing incorrect data types for bit slicing and struct

---

python/heterocl/tensor.py
tests/issues/test_issue_289.py
tests/test_dsl_basic.py
tests/test_dtype.py
tvm/HalideIR/src/arithmetic/Simplify.cpp
tvm/HalideIR/src/ir/IREquality.cpp
tvm/src/codegen/llvm/codegen_llvm.cc
tvm/src/codegen/llvm/codegen_llvm.h

**Issue**: #289 
**Root cause**: The IR equality pass does not handle the bit slicing cases, which leads to segfault.
**Solution**: Make sure all IR nodes are handled correctly in the IR equality pass.
**Test**: `tests/issues/test_issue_289.py`
**Other comments**: We also change the returned data type for bit slicing. It should always be `uint` if the bitwidth can be inferred. In this PR, we also introduce the reverse bit slicing. Following is an example:
```python
a = 0b10010010
```
Similarly, we can also set bit slices in reverse.
```python
a = 0b10010010
```

[API] Fix bit slicing operations & Introduce reverse slicing

---

hlib/python/hlib/op/extern.py
python/heterocl/compute_api.py
python/heterocl/util.py
tests/test_schedule_compute.py
tvm/src/api/api_ir.cc
tvm/src/codegen/hlsc/codegen_hlsc.cc
tvm/src/codegen/hlsc/codegen_vhls.cc
tvm/src/codegen/llvm/codegen_llvm.cc

This PR enables automatic loop labeling for VHLS code, which would be useful for further analysis of the HLS report. The label is defined as `<stage_name>_<variable_name>`.
As an example, the generated code for GEMM is shown below.
```cpp
C_x: for (bit32 x = 0; x < 64; ++x) {
C_y: for (bit32 y = 0; y < 64; ++y) {
float sum;
sum_x1: for (bit32 x1 = 0; x1 < 1; ++x1) {
sum = 0.000000e+00f;
}
C_ra0: for (bit32 ra0 = 0; ra0 < 64; ++ra0) {
sum = ((A[x][ra0] * B[ra0][y]) + sum);
}
C[x][y] = sum;
}
}
```

[Backend] Automatic loop labeling

---

python/heterocl/tvm/_ffi/runtime_ctypes.py
python/heterocl/types.py
tests/test_dtype.py
tvm/HalideIR/src/base/Type.h
tvm/HalideIR/src/base/TypeBase.h
tvm/dlpack/include/dlpack/dlpack.h
tvm/include/tvm/expr.h
tvm/include/tvm/runtime/c_runtime_api.h
tvm/include/tvm/runtime/packed_func.h
tvm/src/codegen/build_util.cc
tvm/src/codegen/llvm/codegen_cpu.cc
tvm/src/pass/arg_binder.cc
tvm/src/runtime/c_runtime_api.cc

In this PR, we increase our bitwidth support to 2047 bits. Following is the new maximum allowed values.
- Total bitwidth: 2047
- Fractional: 255
For tests, please refer to `test_dtype.py/test_dtype_long_int`.

[Backend] Add Support for Total Bitwidth up to 2047 bits

---

python/heterocl/tensor.py
tests/issues/test_issue_311.py
tests/test_dsl_basic.py

As mentioned in #311, there is index casting issue when inside irregular imperative for loops. Thus, the solution is to remove the casting for tensor indices.
Test case: tests/issues/test_issue_311.py

[API] Fix index casting issue

---

.circleci/config.yml

The latest version of SciPy requires Python 3.7 and Python 3.7 is also stable enough. We can have another test for the older Python version later on if needed.

[CI] Upgrade CI Python Version to 3.7

---

python/heterocl/tvm/stmt.py
tvm/HalideIR/src/ir/Expr.h
tvm/HalideIR/src/ir/IR.cpp
tvm/HalideIR/src/ir/IR.h
tvm/HalideIR/src/ir/IRMutator.cpp
tvm/HalideIR/src/ir/IRMutator.h
tvm/HalideIR/src/ir/IRPrinter.cpp
tvm/HalideIR/src/ir/IRVisitor.cpp
tvm/HalideIR/src/ir/IRVisitor.h
tvm/include/tvm/ir.h
tvm/include/tvm/ir_functor_ext.h
tvm/include/tvm/ir_mutator.h
tvm/include/tvm/ir_visitor.h
tvm/src/api/api_ir.cc
tvm/src/codegen/llvm/codegen_llvm.cc
tvm/src/codegen/llvm/codegen_llvm.h
tvm/src/lang/ir.cc
tvm/src/pass/ir_mutator.cc
tvm/src/pass/ir_visitor.cc

With this PR, a new IR node is introduced. **This PR does not modify any existing logic.** 
The goal of introducing this node is to solve the potential stack-overflow problem. With the current Halide node `Block`, since it only has two body statements, to create a serial of N consecutive statements, we will generate an IR tree of depth N-1. To solve that, a new IR node, `MultiBlock`, is introduced. Instead of building it as a deep tree, this node allows users to create a wide tree with an array of statements. In the future, we should try to replace `Block` with `MultiBlock` as much as possible.

[Pass] Introduce new IR node: MultiBlock

---

python/heterocl/compute_api.py
python/heterocl/schedule.py
tests/test_compute_basic.py
tvm/HalideIR/src/arithmetic/Simplify.cpp
tvm/HalideIR/src/ir/Expr.h
tvm/HalideIR/src/ir/IR.cpp
tvm/HalideIR/src/ir/IR.h
tvm/HalideIR/src/ir/IRMutator.cpp
tvm/HalideIR/src/ir/IRPrinter.cpp
tvm/include/tvm/operation.h
tvm/src/api/api_ir.cc
tvm/src/api/api_lang.cc
tvm/src/codegen/codegen_c.cc
tvm/src/codegen/codegen_c.h
tvm/src/codegen/hlsc/codegen_hlsc.cc
tvm/src/codegen/hlsc/codegen_hlsc.h
tvm/src/codegen/hlsc/codegen_vhls.cc
tvm/src/codegen/llvm/codegen_llvm.cc
tvm/src/codegen/llvm/llvm_module.cc
tvm/src/op/extern_op.cc
tvm/src/pass/ir_mutator.cc
tvm/src/pass/lift_allocate_attrs.cc
tvm/src/pass/lift_attr_scope.cc
tvm/src/pass/lower_tvm_builtin.cc
tvm/src/pass/storage_flatten.cc
tvm/src/schedule/schedule_ops.cc

In this PR, we develop a new API `hcl.const_tensor` that allows users to declare a constant tensor. The initial values can be given from a Python list or a NumPy array. Example usage is as follows.
```python
def kernel():
A = hcl.const_tensor([[2, 2], [3, 4], [1, 2]], "A")
return hcl.compute(A.shape, lambda x, y: A[x, y]+1, "B")
s = hcl.create_schedule([], kernel)
f = hcl.build(s)
```
Or, with a NumPy array
```python
def kernel():
A = hcl.const_tensor(np.array([[2, 2], [3, 4], [1, 2]]), "A")
return hcl.compute(A.shape, lambda x, y: A[x, y]+1, "B")
s = hcl.create_schedule([], kernel)
f = hcl.build(s)
```
Since they are constant tensors, we do not allow users to initialize a constant tensor from another HeteroCL tensor. Moreover, in this PR, we also implement the codegen for HLS C. The …

[API][Backend] Add Support for Constant Tensors

---

tests/test_compute_basic.py

The previous unit tests for constant tensors were designed incorrectly. The tested bitwidth range does not match the generated random number range. This PR fixed that.

[Testing] Fix const tensor tests to exclude overflow

---

tests/__test_codegen_harness.py
tests/test_codegen_aocl.py
tests/test_codegen_ihls.py
tests/test_codegen_vhls.py
tvm/src/codegen/codegen_c.cc
tvm/src/codegen/codegen_c.h
tvm/src/codegen/merlinc/codeanalys_merlinc.cc
tvm/src/codegen/merlinc/codeanalys_merlinc.h

This PR does two things.
1. Add a default method for `Print` stmt in codegen. For now, we simply skip the stmt. In the future, we can customize the print messages for each backend.
2. Restructure the codegen tests. Extract common test patterns into `__test_codegen_harness.py`.

[Backend][Testing] Fix codegen with Print stmt; Restructure codegen tests

---

python/heterocl/debug.py
python/heterocl/tensor.py
python/heterocl/tvm/expr.py
tests/issues/test_issue_342.py

**Solved Issue**: #342 
**Reason and solution**: When operating with NumPy numbers (e.g., `+`, `>`), if we put NumPy numbers on LHS, it will trigger NumPy's operators instead of HeteroCL's. Thus, it generates errors. The existing error message does not show the correct information. This PR fixes the output error messages.
**Test case**: tests/issues/test_issue_342.py

[API] Generate correct error message when operating with NumPy numbers

---

python/setup.py

```shell
Installed /home/circleci/.local/lib/python3.7/site-packages/PyYAML-5.4.1-py3.7-linux-x86_64.egg
Searching for keras-applications>=1.0.6
Reading https://pypi.org/simple/keras-applications/
Downloading https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl#sha256=df4323692b8c1174af821bf906f1e442e63fa7589bf0f1230a0b6bdc5a810c95
Best match: Keras-Applications 1.0.8
Processing Keras_Applications-1.0.8-py3-none-any.whl
Installing Keras_Applications-1.0.8-py3-none-any.whl to /home/circleci/.local/lib/python3.7/site-packages
Adding Keras-Applications 1.0.8 to easy-install.pth file
Installed /home/circleci/.local/lib/python3.7/site-packages/Keras_Applications-1.0.8-py3.7.egg
error: decorator …
```

[CI] Use decorator=4.4.2 to avoid pkg incompatibility in installation 

---

tvm/src/codegen/build_util.cc

Switch back to multi-dim array representation for interface argument in Vivado HLS code generator.

[Codegen] Fix data type error in VHLS test bench generator

---

python/heterocl/tensor.py
tests/issues/test_issue_368.py
tests/test_api.py

Currently, we only allow users to access the `shape` property of a tensor. In this PR, we extend the use of `shape` to a tensor slice. We follow the same semantic as NumPy. For example,
```python
A = hcl.placeholder((2, 3, 4))
A.shape           # (2, 3, 4)
A[0].shape        # (3, 4)
A[0][1].shape     # (4,)
A[0][1][2].shape  # ()
```

[API] Add "shape" property to tensor slice

---

hlib/python/setup.py
python/setup.py
tvm/CPPLINT.cfg

In this PR, due to the update of Python cpplint package, a new rule is excluded for our repo. Also, we fixed the version of package `networkx` to avoid Numpy version mismatch.

[CI] Fix CPPLINT tests and fix version for networkx

---

tests/issues/test_issue_398.py
tests/test_api.py
tvm/HalideIR/src/arithmetic/Simplify.cpp

**Fixed issue** #398
**Detailed description:**
In this PR, we remove unnecessary simplification for bitwise operators. In the original code base, inside `Simplify.cpp`, the bitwise_and will become a modular operator in certain cases, which is not necessary and can be wrong. This logic is now removed in this PR.
**Link to the tests:**
Two tests are added. [One](https://github.com/seanlatias/heterocl/blob/quick_fix/tests/issues/test_issue_398.py) under tests/issues and [the other](https://github.com/seanlatias/heterocl/blob/8c45e709b912120dc92b2a64966e94989c413ab2/tests/test_api.py#L122) for more general testing under tests/test_api.py.

[Pass] Remove Unnecessary Simplification for Bitwise Operators

---

python/heterocl/api.py
tests/issues/issue_408_code.py
tests/issues/test_issue_408.py
tests/test_api_print.py
tests/test_api_print_cases/print_tensor_2D_rect.py

**Fixed issue:** #408
In this PR, we make sure the output shape is the same as the input shape. The bug was from incorrect loop bound (tensor shape) collection when printing the tensor.
**Link to the tests:** 
tests/issues/test_issue_408.py
A separate test is also added under tests/test_api_print.py

[API] Fix hcl.print with Incorrect Output Shape

---

python/heterocl/types.py
tests/issues/test_issue_410.py

**Fixed issue:** #410
Enable the string initialization in types.py. Also, added a `__eq__` method in the Type base class for checking the equivalence between types.
**Link to the tests:**
tests/issues/test_issue_410.py

[API] Allow string initialization for `hcl.struct`

---

python/heterocl/api.py
python/heterocl/config.py
python/heterocl/debug.py
python/heterocl/tvm/module.py
tests/test_api_assert.py
tests/test_api_assert_cases/basic_assert_tests.py
tests/test_api_assert_cases/dsl_def_assert_tests.py
tests/test_api_assert_cases/memory_assert_tests.py
tvm/src/codegen/llvm/codegen_llvm.cc
tvm/src/codegen/llvm/codegen_llvm.h
tvm/src/codegen/llvm/llvm_module.cc

**Fixed issue:** #413 
Now when `hcl.assert` failed, an exception will be raised. Users can turn off the exception by setting `hcl.init(raise_assert_exception=False)`. An example program to catch the assertion fail looks like this
```python
def kernel(...):
...
hcl.assert_(xxx)
s = hcl.create_schedule()
f = hcl.build(s)
try:
f(args)
except hcl.debug.AssertError:
```
**Link to the tests:** 
Add one test under test_api_assert.py.

[API] Raise exception when `hcl.assert` fails

---

tests/issues/test_issue_194.py
tests/issues/test_issue_207.py
tests/issues/test_issue_275.py
tests/issues/test_issue_304.py
tests/issues/test_issue_416.py
tvm/src/codegen/hlsc/codegen_vhls.cc
tvm/src/codegen/opencl/codegen_xocl_host.cc

**Detailed description:** The OpenCL host generator does not generate OpenCL buffer for scalar input/output. 
**Link to the tests:** tests/issues/test_issue_416.py
**Detailed description:** The HLS code generator binds multiple different off-chip memory accesses to the same AXI controller, and thus the design cannot pass dataflow check. 
**Link to the tests:** tests/issues/test_issue_275.py
**Detailed description:** Generate multi-dim array for top-level function. This will avoid some synthesis errors that may happen in Vivado HLS of older versions.
**Link to the tests:** tests/issues/test_issue_194.py
**Detailed description:** Added auto-data placement (i.e., if programmers do not apply .to primitive at all, the whole program is placed to FPGA by default).
**Link to the tests:** …

[Backend] Fix issues in OpenCL/HLSC code generator

---

.github/workflows/zhang-21.yml

**Add feature:** add CD/CI testing on our local server. Right now, some test cases requiring EDA tools are skipped in CD/CI testing on CircleCI servers. This PR will add CI/CD testing on our local server, which enables us to verify our design with EDA tools like Vivado HLS or AOC.
**How to use the new feature:** The local CI/CD testing process is completely automatic. 
**Detailed description:**. For each commit, the web hook on github will automatically inform the local CI/CD runner installed on our local server to pull back the latest changes and run the test cases. The test result will be sent back to github repo and be displayed as the status (i.e., passed or failed) of the commit.
**Link to the tests:** TBA

[TEST] Add CI/CD testing on local servers 

---

.github/workflows/zhang-21.yml

**Add feature:** add CD/CI testing on our local server. Right now, some test cases requiring EDA tools are skipped in CD/CI testing on CircleCI servers. This PR will add CI/CD testing on our local server, which enables us to verify our design with EDA tools like Vivado HLS or AOC.
**How to use the new feature:** The local CI/CD testing process is completely automatic. 
**Detailed description:**. For each commit, the webhook on github will automatically inform the local CI/CD runner installed on our local server to pull back the latest changes and run the test cases. The test result will be sent back to github repo and be displayed as the status (i.e., passed or failed) of the commit.
**Link to the tests:** TBA

[TEST] Update testing rules for local CI/CD runners

---

.circleci/config.yml
hlib/python/setup.py
python/setup.py

**Fixed issue:** the install script automatically chooses the latest version of scipy, and this will result in a version conflict and installation error
**Detailed description:** fix scipy version to be 1.7.2
**Link to the tests:** N/A

[CI/CD] Fix scipy version to be 1.7.2 in CI/CD

---

.github/workflows/main.yml
tests/issues/test_issue_450.py
tvm/HalideIR/src/arithmetic/Simplify.cpp

**Fixed issue:** #450 
Minimal test case: in the top-level `else` branch, the `var` has been updated before going in another if statement. Namely, the second `with hcl.if_(var == 0)` is not always false, and should not be optimized away.
```python
def two_stage(A):
var = hcl.scalar(0, "v", dtype=hcl.UInt(32))
var.v = 1
with hcl.if_(var == 0):
hcl.print((),"A\n")
with hcl.else_():
var.v = var - 1
with hcl.if_(var == 0):
hcl.print((),"B\n")
return A
```
This is the buggy IR generated by HCL before the ifx.
```c++
// generated IR
produce _top {
// attr [0] extern_scope = 0
// attr [v] storage_scope = "global"
allocate v[uint32 * 1]
produce v {
// attr [0] extern_scope = 0
for "stage_name"="v" (x, 0, 1) {
v[x] = (uint32)0
}
}
v[0] = (uint32)1
if ((v[0] == …
```

[Fix] Halide IR Simplify pass wrongly optimizes away if condition 

---

tests/issues/test_issue_383.py
tvm/src/codegen/codegen_c.cc

**Fixed issue:** #383
**Detailed description:**  
The `ExtractDType` function that returns data type for given expression did not take `Select` and `Call` into consideration. This PR adds these cases and a corresponding test case. 
**Link to the tests:** `tests/issues/test_issue_383.py`

[Fix] Fix for Complex Select Expression: issue #383

---

python/heterocl/tensor.py
tests/issues/test_issue_386.py
tvm/src/codegen/llvm/codegen_llvm.cc
tvm/src/pass/generate_reuse_buffer.cc
tvm/src/pass/ir_util.h

**Fixed issue:** #386 
The cast operations on tensor indices are incorrectly removed by `CastRemover`, which causes binary operation data type mismatch. This PR fixes this issue by removing the CastRemovers and enforcing indices to have i32 data type for LLVM backend. 
**Link to the tests:** `tests/issues/test_issue_386.py`

[Fix] Remove CastRemover for Tensor Indices (issue #386)

---

tests/issues/test_issue_458.py
tvm/src/codegen/code_analysis.cc
tvm/src/codegen/code_analysis.h
tvm/src/codegen/hlsc/codegen_shls.cc

**Fixed issue:** #458
This PR fixes two things:
- The `code_analysis.h` pass doesn't have `Assert` stmt visitor, which causes an error saying that it doesn't support this node. This PR adds this visitor.
- SHLS's implementation of `Assert` node was wrong, we should use `SC_ASSERT` instead of `assert`.
**Link to the tests:** [tests/issues/test_issue_458.py](https://github.com/zzzDavid/heterocl/blob/issue458/tests/issues/test_issue_458.py)

[Fix] Issue #458: Add SHLS Support for hcl.assert_

---

tests/issues/test_issue_459.py
tvm/src/codegen/hlsc/codegen_shls.cc

**Fixed issue:** #459
**Detailed description:**
Issue #459 was caused by `big_uint` and `big_int` not printed. This PR fixes this issue and verifies that `big_int` and `big_uint` are printed. 
**Link to the tests:** [tests/issues/test_issue_459.py](https://github.com/zzzDavid/heterocl/blob/issue459/tests/issues/test_issue_459.py)

[Fix] Issue459: SHLS Backend Big UInt Type Printing

---

heterocl/ast/ir_builder.py
tests/op/test_bconv.py

- Fix issue #477 and add two test bconv cases with `hcl.buffer_at`
- Cause of the problem: a typo (`hcl_d.BufferAt` -> `hcl_d.BufferAtOp`)
We had no test cases with `hcl.buffer_at` in the test suite, so this problem was not caught.
- `tests/ops/test_bconv.py::test_bconv_nhwc_buffer_at`: binary convolution with buffer at and reuse at
- `test/ops/test_bconv.py::test_packed_bconv_nhwc_threshold_bufferat`: packed bconv + BN threshold with buffer at and reuse at

[IRBuilder] Fix #477 `buffer_at` not built in IR

---

heterocl/ast/ast.py
heterocl/ast/ir_builder.py
heterocl/operation.py
heterocl/utils.py
tests/op/test_bconv.py
tests/test_compute_basic.py

This PR fixes #480.
It also provides a way to support arbitrary bitwidth NumPy array as input. Please take a look and see if the function argument part can be changed correspondingly. @zzzDavid

[Op] Remove redundant cast op for integer const_tensor

---

.circleci/task_lint.sh
heterocl/ast/ast.py
scripts/lint/git-black.sh

The current CI script only compares the format with the previous commit in the current branch, but does not compare it with the main branch, causing the failure of #481. This PR adds format checking with the main branch, and updates the corresponding hcl-dialect commit to depict the latest license change.

[CI] Fix CI formatting

---

docs/source/genindex.rst
heterocl/ast/ir_builder.py
scripts/lint/git-black.sh
setup.py

This PR fixes the failure in #486 (which is because the PR branch is not up-to-date and does not cover necessary CI formatting tests).
Also, it fixes the insertion point for `GlobalOp`. We should follow C/C++ convention that declare all the required variables **before** usage. For example, instead of
```mlir
module {
func.func @top(%arg0: memref<1x16x30x30xi32>) -> memref<1x16x30x30x!hcl.Fixed<26, 20>> attributes {itypes = "s", otypes = "_"} {
...
}
memref.global "private" constant @bn_weight : memref<16xi64> = dense<[...]>
memref.global "private" constant @bn_bias : memref<16xi64> = dense<[...]>
}
```
We should do the following
```mlir
module {
memref.global "private" constant @bn_weight : memref<16xi64> = dense<[...]>
memref.global "private" constant @bn_bias : memref<16xi64> = …
```

[Fix] Formatting and insertion point

---

heterocl/build_module.py

This PR has only one line of change, it sets the optimization level in ExecutionEngine to 3, the highest level.

[Backend][LLVM] Set opt-level to 3

---

heterocl/types.py
tests/test_dtype.py

This PR fixes #492, the `__eq__` implementation of `Type` class. The previous implementation did not compare the type of `Type` instances. 
- Added type comparision in `Type.__eq__`
- Added `fracs` and `exponent` attr in float32 and float64 types
`tests/test_dtype.py::test_type_comparision`

[Type] Fix type comparison (Fix #492)

---

heterocl/ast/ast.py
heterocl/ast/ir_builder.py
heterocl/ast/type_rules.py
heterocl/intrin.py

This PR adds support for math operations including `expr`, `pow`, `log`, `log2`, `log10`, `sin`, `cos`, `tanh`.
- Type rules for math operations
- IRBuilder method for math operations
`hcl.tan` is not available at the moment. This is because LLVM 15.0 misses this rewrite pattern: 
[populateExpandTanPattern](https://mlir.llvm.org/doxygen/namespacemlir.html#a84e85fbc0b8884dd2405be7b78b0c8e7). `hcl.tan` will be added in future releases after we bump LLVM version.

[Op] Add math operations

---

.circleci/config.yml
requirements.txt

`attrs` is added to the dependency to solve this issue:
```
heterocl/devices.py:9:0: E0401: Unable to import 'attr' (import-error)
heterocl/tools.py:7:0: E0401: Unable to import 'attr' (import-error)
```
I think we should also specify a version of black and pylint to use. Pylint and black may have different check results with different versions. The undergrad team has encountered this issue a few time, I think it's easier to just fix a version on CI and local test copy.

[CI] Add attrs and specify black, pylint version

---

heterocl/ast/ast.py
heterocl/ast/ir_builder.py
tests/test_dtype.py

This PR fixes an issue with FP to Index type cast op. 
Building `arith.fptoui` for fp -> index cast fails at MLIR verification with message:
```
arith.fptoui result #0 must be signless-fixed-width-integer-like, but got index
```
The solution is to cast FP to UI first, then use `arith.index_cast` to cast UI to Index.

[IRBuilder] Fix FP to Index cast

---

heterocl/__init__.py
heterocl/ast/ir_builder.py
heterocl/build_module.py
heterocl/ir/__init__.py
heterocl/ir/transform.py
heterocl/primitives/__init__.py
heterocl/primitives/base.py
heterocl/primitives/buffer_at.py
heterocl/primitives/compute_at.py
heterocl/primitives/fuse.py
heterocl/primitives/parallel.py
heterocl/primitives/partition.py
heterocl/primitives/pipeline.py
heterocl/primitives/reform.py
heterocl/primitives/reorder.py
heterocl/primitives/replace.py
heterocl/primitives/reshape.py
heterocl/primitives/reuse_at.py
heterocl/primitives/split.py
heterocl/primitives/systolic.py
heterocl/primitives/tile.py
heterocl/primitives/unroll.py
heterocl/schedule.py
tests/test_udp.py

This PR refactors the schedule primitives by decoupling them from the `Schedule` and `Stage` classes and maintaining each of them in a separate file. It makes the code structure more clear and enables users to plug in their customizations as a primitive.
The following code shows an example that creates buffers for each function argument. Users can inherit from our base `Primitive` class and define their own primitive by implementing the `apply` function. We provide several helper functions in `heterocl.ir.transform` to conduct program transformations, so users can write a few lines of code to create intermediate buffers or implement more complicated optimizations. After implementing the transformation, users only need to call the `register_primitive` decorator, and HeteroCL will …

[Primitive] Extensible primitives and transformations in Python

---

.circleci/config.yml
.gitmodules
README.md
heterocl/passes/__init__.py
heterocl/passes/nest_if.py
heterocl/passes/pass_manager.py
heterocl/passes/promote_func.py
setup.py

This PR fixes issue #510, while adding a few more maintenance: 
- Switched `hcl-dialect` remote from ssh to https, so that user does not need to add ssh key when simply cloning the package.
- Adds `harness` as package data, so that `harness` is also copied to `site-packages/heterocl` during installation.
- Fixed a typo in README.

[Python Package] Update Python package settings (Fix #510)
